formatter: markdown table
recursive:
  enabled: false
  path: ./modules
sort:
  enabled: true
  by: name
output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
